version: "3.9"
services:
  portifolio-my-app:
      build: ./my-app
      container_name: portifolio-my-app
      networks:
        default:
          ipv4_address: 172.25.0.9
      ports:
        - 3001:3001
  portifolio-my-app-2:
      build: ./my-app
      container_name: portifolio-my-app-2
      networks:
        default:
          ipv4_address: 172.25.0.10
      ports:
        - 3002:3002
      
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
